import type { MeisterwegBundle, Player, SeasonStats } from './types';
import { getBuiltinTemplate } from './constraints';

// バンドルから人間が読めるMarkdownのキャリアレポートを生成する。
export function buildMarkdownReport(b: MeisterwegBundle): string {
  const L: string[] = [];
  const seasonsById = new Map(b.seasons.map((s) => [s.id, s]));
  const playersById = new Map(b.players.map((p) => [p.id, p]));
  const seasonLabel = (id: string) => seasonsById.get(id)?.label ?? '—';

  L.push(`# ${b.career.name} — Meisterweg レポート`);
  L.push('');
  L.push(`- チーム：${b.career.team_name}`);
  L.push(`- 出力日時：${new Date(b.exported_at).toLocaleString('ja-JP')}`);
  L.push(`- シーズン数：${b.seasons.length} / 選手数：${b.players.length}`);
  L.push('');

  // シーズン別チーム成績
  L.push('## チーム成績');
  for (const s of b.seasons) {
    const recs = b.team_records.filter((r) => r.season_id === s.id);
    if (recs.length === 0) continue;
    L.push('');
    L.push(`### ${s.label}`);
    L.push('');
    L.push('| 区分 | 大会 | 順位/到達 | 勝 | 分 | 敗 | 得 | 失 |');
    L.push('|---|---|---|--:|--:|--:|--:|--:|');
    for (const r of recs) {
      const pos = r.competition_type === '大陸間クラブ選手権' && r.league_phase_position
        ? `LP${r.league_phase_position} / ${r.final_position}` : r.final_position;
      L.push(`| ${r.competition_type} | ${r.competition_name} | ${pos || '—'} | ${r.wins} | ${r.draws} | ${r.losses} | ${r.goals_for} | ${r.goals_against} |`);
    }
  }
  L.push('');

  // 選手一覧（在籍）
  L.push('## 選手');
  L.push('');
  L.push('| 選手 | Pos | 国籍 | 加入 | 加入OVR | 現OVR | 状態 |');
  L.push('|---|---|---|---|--:|--:|---|');
  for (const p of b.players) {
    const cur = currentOvr(p, b.season_stats);
    L.push(`| ${p.name} | ${p.position} | ${p.nationality || '—'} | ${seasonLabel(p.join_season_id)} | ${p.join_ovr} | ${cur} | ${p.current_status} |`);
  }
  L.push('');

  // 移籍（退団）履歴
  const departures = b.transfers.filter((t) => (t.kind ?? 'departure') === 'departure');
  if (departures.length) {
    L.push('## 移籍（退団）');
    L.push('');
    L.push('| シーズン | 選手 | 移籍先 | 種別 | 移籍金 |');
    L.push('|---|---|---|---|--:|');
    for (const t of departures) {
      const p = playersById.get(t.player_id);
      L.push(`| ${seasonLabel(t.season_id)} | ${p?.name ?? '—'} | ${t.destination || '—'} | ${t.type} | €${t.fee.toLocaleString('ja-JP')} |`);
    }
    L.push('');
  }

  // シーズンメモ
  const memos = b.season_memos.filter((m) => m.body.trim() !== '');
  if (memos.length) {
    L.push('## シーズンメモ');
    for (const s of b.seasons) {
      const ms = memos.filter((m) => m.season_id === s.id);
      if (ms.length === 0) continue;
      L.push('');
      L.push(`### ${s.label}`);
      for (const m of ms) {
        L.push('');
        L.push(`**${m.month}**`);
        L.push('');
        L.push(m.body);
      }
    }
    L.push('');
  }

  // 縛り
  if (b.constraints.length) {
    L.push('## 縛り');
    L.push('');
    for (const c of b.constraints) {
      const tpl = getBuiltinTemplate(c.template_key);
      const label = tpl?.label ?? 'カスタム縛り';
      const kind = c.is_auto ? '自動判定' : '手動';
      L.push(`- **${label}**（${kind}）${c.note ? ' — ' + c.note : ''}${c.penalty ? `／違反時：${c.penalty}` : ''}`);
    }
    L.push('');
  }

  L.push('---');
  L.push('*Generated by Meisterweg*');
  return L.join('\n');
}

function currentOvr(p: Player, stats: SeasonStats[]): number {
  const mine = stats.filter((s) => s.player_id === p.id && s.end_ovr != null);
  if (mine.length === 0) return p.join_ovr;
  // season順は保証されないため、end_ovrの最後＝最大シーズンを使うのは難しい。簡易に最大値ではなく加入時を基準に最新値。
  // ここでは end_ovr の中で最も新しいもの（配列末尾）を採用。
  return mine[mine.length - 1].end_ovr ?? p.join_ovr;
}
